name: chatview
description: تطبيق محادثة ومشاركة وسائط متكامل مع نظام VIP

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.18.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.8.0
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  provider: ^6.1.1
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  video_player: ^2.8.0
  webview_flutter: ^4.4.2
  uuid: ^3.0.7
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700

  # تكوين خاص بـ iOS
  info_plist:
    NSCameraUsageDescription: "لتتمكن من مشاركة الصور والفيديوهات"
    NSMicrophoneUsageDescription: "لإجراء المكالمات الصوتية"
    NSPhotoLibraryUsageDescription: "لاختيار الصور للمشاركة"
